sudo: required
services:
  - docker

before_install:
  - docker build -t alex0menshikov/testdocker2-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true alex0menshikov/testdocker2-test npm test -- --coverage

after_success:
  - docker build -t alex0menshikov/testdocker2-client ./client
  - docker build -t alex0menshikov/testdocker2-server ./server
  - docker build -t alex0menshikov/testdocker2-nginx ./nginx
  - docker build -t alex0menshikov/testdocker2-worker ./worker
  - echo "$DOCKER_PWD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push alex0menshikov/testdocker2-client
  - docker push alex0menshikov/testdocker2-server
  - docker push alex0menshikov/testdocker2-nginx
  - docker push alex0menshikov/testdocker2-worker

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "test-docker2"
  env: "TestDocker2-env"
  bucket_name: "elasticbeanstalk-us-east-2-929379175951"
  bucket_path: "test-docker2"
  on:
    branch:  master
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key: "$AWS_SECRET_KEY"
